//*****************************************************************************
// A C++ behavior tree lib https://github.com/Lecrapouille/BehaviorTree
//
// MIT License
//
// Copyright (c) 2024 Quentin Quadrat <lecrapouille@gmail.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//*****************************************************************************

#pragma once

#include "project_info.hpp" // generated by MyMakefile
#include <list>
#include <string>
#include <vector>
#include <fstream>

namespace bt {

//------------------------------------------------------------------------------
#  if defined(__APPLE__)
std::string osx_get_resources_dir(std::string const& file);
#  endif

//------------------------------------------------------------------------------
#  undef GET_DATA_PATH
#  if defined(__APPLE__)
#    define GET_DATA_PATH osx_get_resources_dir("")
#  else
#    define GET_DATA_PATH project::info::data_path
#  endif

// *****************************************************************************
//! \brief Class manipulating a set of paths for searching files in the same
//! idea of the Unix environment variable $PATH. Paths are separated by ':' and
//! search is made left to right. Ie. "/foo/bar:/usr/lib/"
// *****************************************************************************
class Path
{
public:

    //--------------------------------------------------------------------------
    //! \brief Empty constructor. No path is defined.
    //--------------------------------------------------------------------------
    Path() = default;

    //--------------------------------------------------------------------------
    //! \brief Constructor with a given path. Directories shall be separated
    //! by the character given by the param delimiter.
    //! Example: Path("/foo/bar:/usr/lib/", ':').
    //--------------------------------------------------------------------------
    Path(std::string const& path, char const delimiter = ':');

    //--------------------------------------------------------------------------
    //! \brief Destructor.
    //--------------------------------------------------------------------------
    ~Path() = default;

    //--------------------------------------------------------------------------
    //! \brief Append a new path. Directories are separated by the delimiter char
    //! (by default ':'). Example: add("/foo/bar:/usr/lib/").
    //--------------------------------------------------------------------------
    void add(std::string const& path);

    //--------------------------------------------------------------------------
    //! \brief Replace the path state by a new one. Directories are separated by
    //! the delimiter char (by default ':'). Example: reset("/foo/bar:/usr/lib/").
    //--------------------------------------------------------------------------
    void reset(std::string const& path);

    //--------------------------------------------------------------------------
    //! \brief Erase the path.
    //--------------------------------------------------------------------------
    void clear();

    //--------------------------------------------------------------------------
    //! \brief Erase the given directory from the path if found.
    //--------------------------------------------------------------------------
    void remove(std::string const& path);

    //--------------------------------------------------------------------------
    //! \brief Find if a file exists in the search path. Note that you have to
    //! check again the existence of this file when opening it (with functions
    //! such as iofstream, fopen, open ...). Indeed the file may have been
    //! suppress since this method have bee called.
    //!
    //! \return the full path (if found) and the existence of this path.
    //!
    //--------------------------------------------------------------------------
    std::pair<std::string, bool> find(std::string const& filename) const;

    //--------------------------------------------------------------------------
    //! \brief Return the full path for the file (if found) else return itself.
    //! Beware of race condition: even if found the file may have suppress after
    //! this function has been called.
    //--------------------------------------------------------------------------
    std::string expand(std::string const& filename) const; // FIXME retourner pair<string,RD/WR>

    //--------------------------------------------------------------------------
    //! \brief Return the container of path
    //--------------------------------------------------------------------------
    std::vector<std::string> pathes() const;

    //--------------------------------------------------------------------------
    //! \brief Return pathes as string. The first path is always ".:"
    //--------------------------------------------------------------------------
    std::string toString() const;  

    bool open(std::string& filename, std::ifstream& ifs,
              std::ios_base::openmode mode = std::ios_base::in) const;
    bool open(std::string& filename, std::ofstream& ifs,
              std::ios_base::openmode mode = std::ios_base::out) const;
    bool open(std::string& filename, std::fstream& ifs,
              std::ios_base::openmode mode = std::ios_base::in | std::ios_base::out) const;
protected:

    //--------------------------------------------------------------------------
    //! \brief Slipt paths separated by delimiter char into std::list
    //--------------------------------------------------------------------------
    void split(std::string const& path);

    //--------------------------------------------------------------------------
    //! \brief Return true if the path exists. be careful the file may not
    //! exist after the function ends.
    //--------------------------------------------------------------------------
    bool exist(std::string const& path) const;

protected:

    //! \brief Path separator when several pathes are given as a single string.
    const char m_delimiter = ':';
    //! \brief the list of pathes.
    std::list<std::string> m_search_paths;
};

} // namespace bt